In [1]:
# This is where we are invoking the saved model and using it to predict the values of random numbers.  
# This is not exactly an end point but a manual way to use the model to predict the outcome.  

import sys
import numpy as np
import pandas as pd
import xgboost as xgb

In [2]:
# Load the model that was trained in the cloud
booster = xgb.Booster()

In [3]:
booster.load_model(r'linear_xgboost_model')

In [4]:
regressor = xgb.XGBRegressor()

In [5]:
regressor._Booster = booster

In [6]:
regressor.predict([[1], [2], [3], [4], [5]])

array([11.920725, 18.097332, 20.232351, 25.818325, 32.694294],
      dtype=float32)

In [7]:
regressor.predict([1])

array([11.920725], dtype=float32)

In [8]:
regressor.predict([75])

array([108.23764], dtype=float32)